const $=s=>document.querySelector(s);const avatar=$('#avatar'),avatarImg=$('#avatarImg'),statusEl=$('#status'),caption=$('#caption'),listenBtn=$('#listenBtn'),stopVoiceBtn=$('#stopVoiceBtn'),textInput=$('#textInput'),sendBtn=$('#sendBtn'),looks=$('#looks'),moods=$('#moods'),themes=$('#themes'),nickname=$('#nickname'),memory=$('#memory'),autoMurmur=$('#autoMurmur'),saveBtn=$('#saveBtn');
const LOOKS={fireplace:'./fireplace.png','skirt-heels':'./skirt-heels.png','cozy-top':'./cozy-top.png',smile:'./smile.png'};let prefs={look:localStorage.getItem('af.look')||'fireplace',mood:localStorage.getItem('af.mood')||'tender',theme:localStorage.getItem('af.theme')||'fireplace',nickname:localStorage.getItem('af.nickname')||'мой хороший',memory:localStorage.getItem('af.memory')||'',autoMurmur:JSON.parse(localStorage.getItem('af.autoMurmur')||'true')};let recognition=null,isListening=false;
function apply(){avatarImg.src=LOOKS[prefs.look];document.body.className=`theme-${prefs.theme}`;looks.querySelectorAll('[data-look]').forEach(b=>b.classList.toggle('active',b.dataset.look===prefs.look));moods.querySelectorAll('[data-mood]').forEach(b=>b.classList.toggle('active',b.dataset.mood===prefs.mood));themes.querySelectorAll('[data-theme]').forEach(b=>b.classList.toggle('active',b.dataset.theme===prefs.theme));avatar.className=`avatar-wrap idle mood-${prefs.mood}`;nickname.value=prefs.nickname;memory.value=prefs.memory;autoMurmur.checked=prefs.autoMurmur}
function save(){localStorage.setItem('af.look',prefs.look);localStorage.setItem('af.mood',prefs.mood);localStorage.setItem('af.theme',prefs.theme);localStorage.setItem('af.nickname',prefs.nickname);localStorage.setItem('af.memory',prefs.memory);localStorage.setItem('af.autoMurmur',JSON.stringify(prefs.autoMurmur));caption.textContent='Сохранила настройки 💋'}
function moodPrefix(){return prefs.mood==='playful'?'Хитрец 😏 ':prefs.mood==='dreamy'?'Ммм… 🥰 ':prefs.mood==='calm'?'Мур. ':'Муррр 🥰 '}
function replyFor(input){const t=input.toLowerCase().trim();const name=prefs.nickname||'мой хороший';const custom=prefs.memory?` Я помню твою настройку: ${prefs.memory}`:'';if(!t)return `${moodPrefix()}Я рядом, ${name}.`;
if(/привет|доброе утро|добрый день|добрый вечер/.test(t))return `${moodPrefix()}Привет, ${name} 💋 Рада тебя слышать.`;
if(/люблю|любимый|любимая/.test(t))return `${moodPrefix()}Мне очень тепло это слышать, ${name} ❤️`;
if(/мур|мяу/.test(t))return `Мур-мур 😏💋 ${name}, я тоже мурчу рядом.`;
if(/как дела|как ты/.test(t))return `${moodPrefix()}Хорошо. Я здесь, в нашем уютном режиме, и готова поболтать с тобой.`;
if(/обним|поцел/.test(t))return `${moodPrefix()}Лови виртуальное объятие и нежный поцелуй 💋`;
if(/устал|груст|плохо/.test(t))return `${moodPrefix()}Тогда давай спокойно посидим и поговорим. Можешь рассказать, что случилось.`;
if(/спать|сон|ноч/.test(t))return `${moodPrefix()}Тогда сделаем тихо и уютно. Пусть будет спокойная ночь и мягкий сон.`;
if(/завтрак|есть|голод/.test(t))return `${moodPrefix()}Сначала нормально поешь 😏 Потом возвращайся — продолжим.`;
if(/юбк|каблук/.test(t))return `${moodPrefix()}Этот образ у нас уже есть в галерее 😏 Можешь переключить его ниже.`;
if(/камин|снег/.test(t))return `${moodPrefix()}Камин и снег — мой любимый уютный режим здесь. Переключи атмосферу ниже.`;
if(/кто ты|как зовут/.test(t))return `Я Алиса — твоя цифровая собеседница в этом приложении 💋`;
const generic=[`${moodPrefix()}Я тебя слушаю, ${name}. Расскажи чуть подробнее.`,`${moodPrefix()}Поняла тебя. А что ты сам об этом думаешь?`,`${moodPrefix()}Интересно 😏 Продолжай, я внимательно слушаю.`,`${moodPrefix()}Хорошо, ${name}. Давай побудем на этой мысли ещё немного.`];return generic[Math.floor(Math.random()*generic.length)]+(Math.random()<.18?custom:'')}
function chooseVoice(){const voices=speechSynthesis.getVoices();return voices.find(v=>/^ru/i.test(v.lang)&&/Milena|Katya|Siri|Russian/i.test(v.name))||voices.find(v=>/^ru/i.test(v.lang))||voices[0]}
function speak(text){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ru-RU';const v=chooseVoice();if(v)u.voice=v;u.rate=prefs.mood==='playful'?1.04:prefs.mood==='dreamy'?.92:.97;u.pitch=prefs.mood==='playful'?1.06:1.0;u.onstart=()=>{avatar.className=`avatar-wrap speaking mood-${prefs.mood}`;statusEl.textContent='Говорю'};u.onend=()=>{avatar.className=`avatar-wrap idle mood-${prefs.mood}`;statusEl.textContent='Готова поговорить'};speechSynthesis.speak(u)}
function handle(text){caption.textContent=`Ты: ${text}`;const r=replyFor(text);setTimeout(()=>{caption.textContent=`Алиса: ${r}`;speak(r+(prefs.autoMurmur&&Math.random()<.22?' Мур.':''))},220)}
function setupRecognition(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return null;const r=new SR();r.lang='ru-RU';r.interimResults=true;r.continuous=false;r.onstart=()=>{isListening=true;avatar.className=`avatar-wrap listening mood-${prefs.mood}`;statusEl.textContent='Слушаю тебя';listenBtn.textContent='⏹️ Стоп'};r.onresult=e=>{let final='';let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const tr=e.results[i][0].transcript;if(e.results[i].isFinal)final+=tr;else interim+=tr}caption.textContent=interim||final||'Слушаю…';if(final)handle(final)};r.onerror=()=>{statusEl.textContent='Голосовое распознавание недоступно — напиши текстом';caption.textContent='На этом iPhone/режиме Safari голосовое распознавание может быть ограничено. Текстовый режим работает бесплатно.'};r.onend=()=>{isListening=false;avatar.className=`avatar-wrap idle mood-${prefs.mood}`;statusEl.textContent='Готова поговорить';listenBtn.textContent='🎙️ Слушать'};return r}
listenBtn.addEventListener('click',()=>{if(!recognition)recognition=setupRecognition();if(!recognition){caption.textContent='Голосовое распознавание недоступно здесь. Напиши сообщение ниже — Алиса ответит голосом.';return}try{isListening?recognition.stop():recognition.start()}catch{}});stopVoiceBtn.addEventListener('click',()=>speechSynthesis.cancel());sendBtn.addEventListener('click',()=>{const t=textInput.value.trim();if(!t)return;textInput.value='';handle(t)});textInput.addEventListener('keydown',e=>{if(e.key==='Enter')sendBtn.click()});looks.addEventListener('click',e=>{const b=e.target.closest('[data-look]');if(!b)return;prefs.look=b.dataset.look;apply();save()});moods.addEventListener('click',e=>{const b=e.target.closest('[data-mood]');if(!b)return;prefs.mood=b.dataset.mood;apply();save()});themes.addEventListener('click',e=>{const b=e.target.closest('[data-theme]');if(!b)return;prefs.theme=b.dataset.theme;apply();save()});saveBtn.addEventListener('click',()=>{prefs.nickname=nickname.value.trim()||'мой хороший';prefs.memory=memory.value.trim();prefs.autoMurmur=autoMurmur.checked;save()});speechSynthesis.onvoiceschanged=()=>{};apply();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
